'use client';

import { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

const faqs = [
  {
    question: 'Is the exported theme 100% compatible with Shopify Online Store 2.0?',
    answer:
      'Yes. Every theme generated by Antigravity strictly adheres to Shopify OS 2.0 standards. It includes standard JSON templates (`templates/index.json`, `templates/product.json`, `templates/collection.json`, `templates/cart.json`), Liquid layout (`layout/theme.liquid`), modular sections with valid `{% schema %}` blocks, snippets, and `config/settings_schema.json`.',
  },
  {
    question: 'Can I edit the theme settings inside Shopify’s native Theme Customizer?',
    answer:
      'Absolutely. All generated sections declare configurable schema settings (such as headings, body text, colors, image pickers, and repeatable blocks). When you upload the theme to Shopify, you can visually customize every section just like any premium commercial theme.',
  },
  {
    question: 'Do I need to run terminal commands, npm, or build tools to use the exported theme?',
    answer:
      'No local build step is required! The downloaded ZIP is already fully compiled and packaged. Simply log in to your Shopify Admin, navigate to Online Store > Themes > Add Theme > Upload zip file, and publish.',
  },
  {
    question: 'How are images generated and served?',
    answer:
      'Theme images are powered by ImageKit. During generation, AI produces tailored product lifestyle imagery and banner mockups. Images are served via ImageKit’s global edge CDN with automatic WebP/AVIF format optimization and responsive resizing.',
  },
  {
    question: 'What pages are created with each theme generation?',
    answer:
      'Each project includes the 5 core storefront pages: Homepage, Product Details (with variant selection and galleries), Collections Grid (with sorting and filters), Cart (with drawer and page views), and Custom Story/About Page.',
  },
  {
    question: 'How does the scoped inline AI editing work?',
    answer:
      'Inside the visual builder, you can click on any individual heading, button, card, or section and type a natural language edit. Our AI produces a targeted DOM patch rather than regenerating the entire page, ensuring zero downtime and full revision history with instant undo.',
  },
];

export default function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="relative py-24 bg-neutral-50/60 text-neutral-900 border-b border-neutral-200/80">
      <div className="mx-auto max-w-4xl px-6 sm:px-8">
        {/* Section Header */}
        <div className="text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#FFCCBC] bg-[#FFF3EE] px-4 py-1.5 text-xs font-semibold text-[#FF3B00]">
            <HelpCircle size={13} />
            <span>FREQUENTLY ASKED QUESTIONS</span>
          </div>
          <h2 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-5xl text-neutral-950">
            Got Questions? We&apos;ve Got Answers.
          </h2>
          <p className="mt-4 text-base text-neutral-600">
            Everything you need to know about the AI theme builder, Shopify OS 2.0 compatibility, and export workflows.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="mt-14 space-y-3.5">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className="overflow-hidden rounded-2xl border border-neutral-200 bg-white transition-all shadow-xs"
              >
                <button
                  type="button"
                  onClick={() => toggle(index)}
                  className="flex w-full items-center justify-between p-6 text-left"
                >
                  <span className="text-sm sm:text-base font-bold text-neutral-950">
                    {faq.question}
                  </span>
                  <span
                    className={`ml-4 grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-neutral-100 text-neutral-600 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 bg-[#FFF3EE] text-[#FF3B00]' : ''
                    }`}
                  >
                    <ChevronDown size={16} />
                  </span>
                </button>
                {isOpen && (
                  <div className="px-6 pb-6 text-xs sm:text-sm leading-relaxed text-neutral-600 border-t border-neutral-100 pt-4 font-normal">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
